export const postStyle = {
    header: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "15px",
      backgroundColor: "#ffffff",
      borderBottom: "1px solid #ddd",
    },
    userInfo: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    avatar: {
      width: "40px",
      height: "40px",
      borderRadius: "50%",
    },
    username: {
      fontSize: "14px",
      fontWeight: "bold",
      color: "#333",
    },
    closeButton: {
      background: "none",
      border: "none",
      fontSize: "18px",
      color: "#333",
      cursor: "pointer",
    },
    postContent: {
      padding: "20px",
      fontSize: "16px",
      lineHeight: "1.6",
      color: "#333",
    },
    postTitle: {
      fontSize: "24px",
      fontWeight: "bold",
      marginBottom: "10px",
    },
    commentsSection: {
      marginTop: "20px",
      padding: "20px",
      backgroundColor: "#f9f9f9",
      border: "1px solid #ddd",
      borderRadius: "8px",
    },
    comment: {
      marginBottom: "15px",
      padding: "15px",
      border: "1px solid #eee",
      borderRadius: "5px",
      backgroundColor: "#ffffff",
    },
    commentHeader: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      marginBottom: "10px",
    },
    commentUser: {
      fontWeight: "bold",
      color: "#555",
    },
    commentText: {
      color: "#333",
    },
    commentPlaceholder: {
      width: "100%",
      height: "80px",
      padding: "10px",
      marginBottom: "15px",
      border: "1px solid #ddd",
      borderRadius: "5px",
      backgroundColor: "#f7f7f7",
      resize: "none",
      maxWidth: "500px",
    },
    addCommentButton: {
      padding: "10px 20px",
      fontSize: "14px",
      color: "#ffffff",
      backgroundColor: "#1563B8",
      border: "none",
      borderRadius: "5px",
      cursor: "pointer",
      display: "flex",
    },
  };
  